name: issue_creation

on:
  schedule:
    - cron: '30 4 * * SUN'
  workflow_dispatch:

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the template
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: Create issues
        uses: gofair-foundation/qualification-issue-creation-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUERYAPI: https://query.knowledgepixels.com/api/RAGltPUzB31SMPior1Tv1qZ7KCYu_YimxxWNp4qCW-Xks/list_nonqualifed_fsr

      
