name: issue_creation

on:
  schedule:
    - cron: '30 4 * * SUN'
  workflow_dispatch:

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - name: Checkout the template
        uses: actions/checkout@v6.0.2
        with:
          ref: badges
          sparse-checkout: |
            .github
      - name: Create issues
        uses: gofair-foundation/qualification-issue-creation-action@v2.0.1
        with:
          milliseconds: 10000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUERYAPI: https://query.knowledgepixels.com/api/RAGltPUzB31SMPior1Tv1qZ7KCYu_YimxxWNp4qCW-Xks/list_nonqualifed_fsr

      # Add an updated badge when the workflow succeeds
      # Create the directory where badges will be saved, if needed
      - name: Create destination directory
        env:
          BADGE_PATH: '.github/badges'
        run: mkdir -p "${BADGE_PATH%/*}"

      - name: Update badge
        uses: emibcn/badge-action@v2.0.4
        with:
          label: 'Issue sync run'
          status: ${{ steps.date.outputs.data }}
          color: 'blue'
          path: "${GITHUB_WORKSPACE}/.github/badges/workflow.svg"
      - name: Upload badge as artifact
        uses: actions/upload-artifact@v7
        with:
          name: badge
          path: "${GITHUB_WORKSPACE}/.github/badges/workflow.svg"
          if-no-files-found: error
      - name: Commit badge
        continue-on-error: true
        env:
          BADGE: "${GITHUB_WORKSPACE}/.github/badges/workflow.svg"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE}"
          git commit -m "Add/Update badge"
      - name: Push badge commit
        uses: ad-m/github-push-action@v1.3.0
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: badges
